# Generated by Django 5.1 on 2024-09-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_education_model_experience_model_interest_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_model',
            name='end_year',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education_model',
            name='start_year',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
