# Generated by Django 5.1 on 2024-09-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_education_model_end_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INTERMEDIATE_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='experience_model',
            name='end_date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience_model',
            name='start_date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
